// <auto-generated />
using FinalRushikPatel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalRushikPatel.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250409150250_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalRushikPatel.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("bit");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Toronto",
                            CountryId = 1,
                            IsCapital = false,
                            Population = 3000000L
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Ottawa",
                            CountryId = 1,
                            IsCapital = true,
                            Population = 1000000L
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Vancouver",
                            CountryId = 1,
                            IsCapital = false,
                            Population = 700000L
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Sydney",
                            CountryId = 2,
                            IsCapital = false,
                            Population = 5000000L
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Melbourne",
                            CountryId = 2,
                            IsCapital = false,
                            Population = 5200000L
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "London",
                            CountryId = 3,
                            IsCapital = true,
                            Population = 9600000L
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Manchester",
                            CountryId = 3,
                            IsCapital = false,
                            Population = 570000L
                        });
                });

            modelBuilder.Entity("FinalRushikPatel.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "England"
                        });
                });

            modelBuilder.Entity("FinalRushikPatel.City", b =>
                {
                    b.HasOne("FinalRushikPatel.Country", "Country")
                        .WithMany("Citties")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FinalRushikPatel.Country", b =>
                {
                    b.Navigation("Citties");
                });
#pragma warning restore 612, 618
        }
    }
}
